M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu26.04.1 date 2026-10-05T12:41:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-05T12:41:07+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X69.246Y-46.869
X75.026Y-46.869
M30
