M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu26.04.1 date 2026-10-05T11:37:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-05T11:37:54+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu26.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X68.992Y-46.869
X74.772Y-46.869
M30
