#!/usr/bin/env bash
# common.sh — shared helpers for the ESP32-S3 (32bit) firmware build scripts.
#
# Sourced by compile.sh / flash.sh / package.sh (which live in the project dir
# as symlinks into this shared tools dir).

# Defaults. Override via environment if needed.
# sdkconfig was generated by ESP-IDF 5.5.1 targeting the esp32s3.
IDF_VERSION="${IDF_VERSION:-v5.5.1}"
IDF_TARGET="${IDF_TARGET:-esp32s3}"

die() {
  echo "Error: $*" >&2
  exit 1
}

# Locate the ESP-IDF installation.
# Order: $IDF_PATH env → ~/esp/esp-idf → ~/esp/esp-idf-<version>.
find_idf() {
  local candidate
  if [[ -n "${IDF_PATH:-}" && -f "$IDF_PATH/export.sh" ]]; then
    echo "$IDF_PATH"
    return 0
  fi
  for candidate in "$HOME/esp/esp-idf" "$HOME/esp/esp-idf-$IDF_VERSION"; do
    if [[ -f "$candidate/export.sh" ]]; then
      echo "$candidate"
      return 0
    fi
  done
  return 1
}

# Source the ESP-IDF environment into the current shell.
activate_idf() {
  local idf_dir
  idf_dir="$(find_idf)" || die "ESP-IDF not found. Run ./setup.sh first."
  # shellcheck source=/dev/null
  source "$idf_dir/export.sh" >/dev/null
  export IDF_TARGET="$IDF_TARGET"
}
